services:
  postgres:
    image: postgres:16
    container_name: cs_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  redis:
    image: redis:7
    container_name: cs_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  minio:
    image: minio/minio
    container_name: cs_minio
    restart: always
    env_file:
      - .env
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data

  app:
    image: cs_app_image
    build: .
    container_name: cs_app
    env_file:
      - .env
    depends_on:
      postgres:
          condition: service_healthy
      redis:
          condition: service_healthy
      minio:
        condition: service_started
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  redis_data:
  minio_data: